### ISSUE TITLE
Load highlights before/after plugins

### ISSUE THREAD

**Issue by trankchung** [AstroNvim/AstroNvim#1380]
### Question

Hi @mehalter,

Is it possible for me to load the `highlights/theme-name.lua` modules before the bufferline plugin? I've made changes to my `highlights/ayu-mirage.lua` but it doesn't take affect when I started neovim. I had to reload the config again once started neovim for it to take affect so I think it has to be config loading order.

Thanks,

**Comment by mehalter** [comment]
This is a good point. I will look into this this upcoming week!

**Comment by trankchung** [comment]
The reason I'm asking for this is I want to use the `highlights/theme-name.lua` to set the `fg` and `bg` as global variables and use it in bufferline and heirline but it's not working. Currently I had to redefine the `fg` and `bg` colors in 3 places; highlights, bufferline, and heirline which is not DRY at all.

**Comment by mehalter** [comment]
Awesome, `heirline` already does this thankfully. Not sure what you did with heirline for it not to work. I just pushed a commit to `bufferline` that reloads it's colors after the astronvim colorscheme event.

**Comment by mehalter** [comment]
The latest commit to nightly will let you reload `bufferline` hightlight groups from the `highlights` table in your user configuration. This resolves this ticket.

**Comment by trankchung** [comment]
@mehalter My theme is `ayu` according to `vim.g.colors_name` so I created `highlights/ayu.lua` with content below and all those highlights work except for `HeirlineNormal` or `HeirlineVisual`. I am using `nightly` release and I have checked the `~/.config/nvim/lua/configs/heirline.lua` and it does have the changes you've made but it still doesn't work.

```
return {
    CursorLine = { bg = "#191e2a" },
    TypeDef        = { fg = "#00cc00" },

    NeoTreeCursorLine   = { bg = "#191e2a" },
    NeoTreeDotfile      = { fg = "#c6a766" },
    NeoTreeTabActive    = { fg = "#ffd580", bold = true },
    NeoTreeTabInactive  = { fg = "#777777" },
    NeoTreeWinSeparator = { fg = "#1f2430", bg = "#1f2430" },

    HeirlineNormal = { fg = "#ffd580" },
    HeirlineVisual = { fg = "#ffffff" },
  }
```

**Comment by mehalter** [comment]
Ah I see @trankchung this is because `neovim-ayu` provides a `lualine` theme which triggers the lualine compatibility. Since Heirline by default doesn't get the colors from highlight groups and most colorschemes provide lualine integration this gives us really good colorscheme integration with our Heirline config.

I guess what I need to do is to change the logic a bit for the Heirline mode stuff to take the lualine integration *only* if the `Heiline` highlights we are specifying Haven't been set. I will get this updated soon!

**Comment by trankchung** [comment]
@mehalter Thank you very much. No need to rush. As always, thanks for being awesome.

**Comment by mehalter** [comment]
@trankchung  just pushed a commit to nightly that should fix this logic :)

**Comment by trankchung** [comment]
@mehalter The new code you pushed worked perfectly for Heirline. However, my original issue still persists. Let me explain what I'm doing and what isn't working.

Using the same `ayu` colorscheme the content of my `highlights/ayu.lua` is as follow.

```lua
  _G.bg = "#1f2430"
  _G.fg = "#ffd580"
  return {
    CursorLine = { bg = "#191e2a" },
    TypeDef    = { fg = fg },
    ...
    HeirLineNormal = { fg = fg },
    HeirLineVisual = { fg = "#64b5dd" },
  }
```

And the content of my `plugins/bufferline.lua` is as follow:

```lua
local highlights = function()
  return {
    background = {
      bg = bg,
    },
    fill = {
      bg = bg,
    },
    separator {
      fg = fg,
    },
}

return {
  highlights = highlights,
  options = { ... },
}
```

What I did above doesn't change bufferline's highlights. It only works after I ran `AstroReload`.

**Comment by mehalter** [comment]
Yeah this isn't a super good way to do this since the bufferline refreshes it's colors from highlight groups when the colorscheme is changed. I'll send you an updated snippet tomorrow that set the appropriate highlight group names rather than relying on this indirection. This will also fix the code being in two different places issue

**Comment by mehalter** [comment]
@trankchung try something like this:

```lua
local bg = "#1f2430"
local fg = "#ffd580"
return {
  CursorLine = { bg = "#191e2a" },
  TypeDef = { fg = fg },

  HeirLineNormal = { fg = fg },
  HeirLineVisual = { fg = "#64b5dd" },

  BufferLineFill = { bg = bg },
  BufferLineBackground = { bg = bg },
  BufferLineSeparator = { fg = fg },
}
```

Then you don't need to change anything in the bufferline config either, just configure the highlights in the `highlights/` folder

**Comment by trankchung** [comment]
@mehalter I actually did this already but there's one little highlight that I can't get working which is the inactive buffer icon. Maybe I'll just post a question/bug on bufferline and see if they can help. I literally took all the BufferLine* highlight groups and set it to a bg and fg colors but the inactive buffer icon wouldn't change.
