### ISSUE TITLE
highlight matching pair

### ISSUE THREAD

**Issue by matyle** [AstroNvim/AstroNvim#1658]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macos13

### Terminal/GUI

iterm2

## AstroNvim
  4   - INFO: AstroNvim Version: unknown
  5   - INFO: Neovim Version: v0.8.3
  6   - OK: Using stable Neovim >= 0.8.0
  7   - OK: `git` is installed: Used for core functionality such as updater and plugin management
  8   - OK: `open` is installed: Used for `gx` mapping for opening files with system opener
      (Optional)
  9   - OK: `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
 10   - OK: `node` is installed: Used for mappings to pull up node REPL (Optional)
 11   - OK: `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
 12   - OK: `btm` is installed: Used for mappings to pull up system monitor (Optional)
 13   - OK: `python` is installed: Used for mappings to pull up python REPL (Optional)
 

### Describe the bug

Highlight matching pair ]for all types of file extensions

### Steps to Reproduce

open file find pair
![1071679054639_ pic](https://user-images.githubusercontent.com/27877040/225909193-e3e5cd94-6ba5-4fbc-a523-aecadf239bcc.jpg)

### Expected behavior

[
![1061679054627_ pic](https://user-images.githubusercontent.com/27877040/225909194-fd84de57-c100-4b9a-b000-c11051e5082d.jpg)

**Comment by matyle** [comment]
The previous version was normal

**Comment by mehalter** [comment]
Fixed in v3.3.2

**Comment by matyle** [comment]
> Fixed in v3.3.2

it did not work, I tried it

**Comment by matyle** [comment]
> This is with v3.3.2
> 
> ![2023-03-17_09:51:01_screenshot](https://user-images.githubusercontent.com/1591837/225924132-6b4ea8af-75d0-4f70-a87a-9ed3429f5949.png)

sorry, I found user /init.lua still have this, so today I never found it

**Comment by laowalter** [comment]
I have been looking for this too, highlight matching pair not long support. I just install astronvim with  

commit 243a18c10532e57934e19d1c3eb696dfc11c3282 (HEAD -> main, origin/main, origin/HEAD)

has not any history commit.

**Comment by mehalter** [comment]
it is supported and working @laowalter It is currently an issue in AstroTheme (https://github.com/AstroNvim/astrotheme/issues/77)

You might want to bump that issue as well
