### ISSUE TITLE
Heirline not updating cursor position in insert mode; only updating in normal mode

### ISSUE THREAD

**Issue by panv-00** [AstroNvim/AstroNvim#1663]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

arch linux

### Terminal/GUI

alacritty

## AstroNvim
  - INFO: AstroNvim Version: v3.3.0
  - INFO: Neovim Version: v0.8.3
  - OK: Using stable Neovim >= 0.8.0
  - OK: `git` is installed: Used for core functionality such as updater and         plugin management
  - OK: `xdg-open` is installed: Used for `gx` mapping for opening files with       system opener (Optional)
  - OK: `lazygit` is installed: Used for mappings to pull up git TUI                (Optional)
  - OK: `node` is installed: Used for mappings to pull up node REPL (Optional)
  - OK: `gdu` is installed: Used for mappings to pull up disk usage analyzer        (Optional)
  - OK: `btm` is installed: Used for mappings to pull up system monitor             (Optional)
  - OK: `python` is installed: Used for mappings to pull up python REPL             (Optional)

### Describe the bug

When in insert mode, the cursor position display in heirline does not change when typing or moving around.

It starts updating when moving around in normal mode

### Steps to Reproduce

just open any document

### Expected behavior

to update in all modes.

**Comment by mehalter** [comment]
This was fixed in 3.3.1 :)

**Comment by panv-00** [comment]
I am running 3.3.2, and the issue is still there.
I even removed and installed fresh... same problem.

https://user-images.githubusercontent.com/84442305/226068689-9fb1f61e-324c-4d9e-974b-b35853eb4263.mp4

**Comment by mehalter** [comment]
I'll check next week

**Comment by mehalter** [comment]
This is resolved on `nightly`. A release to fix this will be released next week
