### ISSUE TITLE
Nerd Fonts v3.0.0 are currently not compatible with AstroNvim

### ISSUE THREAD

**Issue by cebor** [AstroNvim/AstroNvim#1848]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

all

### Terminal/GUI

all

### AstroNvim Health

 -

### Describe the bug

The latest version of Nerd Fonts seems to be no longer compatible with AstroNvim. Some icons are not displayed correctly. E.g. the "X" to close a tab, or the Git Icons.

### Steps to Reproduce

Install 3.0.0 Nerd Font and check the Glyph Icons.

### Expected behavior

Icons should render correctly.

### Screenshots

<img width="682" alt="Screenshot 2023-05-01 at 16 04 30" src="https://user-images.githubusercontent.com/1576120/235549005-2d2aa0e1-b26d-4362-860a-00fe6b0d8abf.png">

**Comment by mehalter** [comment]
Thanks for reporting this! It looks like we are relying on some material icons which were deprecated in the v3.0 release. I'll do an update tomorrow using non-deprecated icons!

**Comment by mehalter** [comment]
This is resolved on `nightly`. I will get this merged in later today

**Comment by wqk151** [comment]
I have updated to the latest version(v3.14.0),the icon still not displayed correctly.
![2023-05-05_09-00-35](https://user-images.githubusercontent.com/18275602/236359178-ebfabdb3-61f2-47f9-9441-03263fb60530.png)

**Comment by mehalter** [comment]
@wqk151 I would recommend hopping on the Discord and asking questions about font configuration. This looks like an issue with fallback fonts and your fonts being incorrectly configured

**Comment by paprikman** [comment]
> @wqk151 I would recommend hopping on the Discord and asking questions about font configuration. This looks like an issue with fallback fonts and your fonts being incorrectly configured

Having a fallback font is not a solution, since it is not possible to setup those in Alacritty and some other terminal emulators. This is also an issue when working from plain tty. Could you, please, provide other solution?

**Comment by mehalter** [comment]
You do not need not set a fallback font, you can just set a properly patched nerd font as your font and it will work.

**Comment by IVIJL** [comment]
Version 3.40.3 ov Astronvim still not displaying icons properly with nerdfonts 3.0.0 any updates on this ? Toml files are not showing the icon for example.

**Comment by paprikman** [comment]
> Version 3.40.3 ov Astronvim still not displaying icons properly with nerdfonts 3.0.0 any updates on this ? Toml files are not showing the icon for example.

I actually got it solved by just downloading and installing fonts from the NerdFonts release in their repository, not form the "downloads" section on the website. Maybe this helps.

**Comment by IVIJL** [comment]
> > Version 3.40.3 ov Astronvim still not displaying icons properly with nerdfonts 3.0.0 any updates on this ? Toml files are not showing the icon for example.
> 
> I actually got it solved by just downloading and installing fonts from the NerdFonts release in their repository, not form the "downloads" section on the website. Maybe this helps.

Actually youre right, also I had 3.0.0 and now is 3.1.1 and 3.1.1 works out of the box, so they probably moved some icons even between 3.0.0 and 3.1.1
