### ISSUE TITLE
Custom luasnippets for .tex  not loading

### ISSUE THREAD

**Issue by basava70** [AstroNvim/AstroNvim#1882]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Ubuntu 22.04

### Terminal/GUI

Gnome

### AstroNvim Health

![Screenshot from 2023-05-09 17-36-06](https://github.com/AstroNvim/AstroNvim/assets/124213816/b8d94764-3e72-42ed-9ef4-74141ba6a9c3)

### Describe the bug

I have a  custom file, I have placed in user/snippets/all.lua. I have added the following in user/init.lua
plugins = {
![Screenshot from 2023-05-09 17-35-18](https://github.com/AstroNvim/AstroNvim/assets/124213816/d7b2160c-606a-4d0a-a9f7-17208bf1aea6)

}
NOTE: I changed it to "from_lua" and not "from_vscode" , as mentioned in the documentation. I had this working in my personal nvim config. But I love astrovim and want to migrate to it.

### Steps to Reproduce

Nothing just unable to add the custom snippets. Its not loading when I type in my .tex file
Also, I use vimtex for my .tex compilation
I have added the following in lua/user/plugins/user.lua
return {

![Screenshot from 2023-05-09 17-38-04](https://github.com/AstroNvim/AstroNvim/assets/124213816/05b063d3-e6c0-4605-ba74-dbea4c458fd7)

}

### Expected behavior

I want the auto snippets to load as I type them

**Comment by basava70** [comment]
I forgot to add my custom snippet file may be it helps
![Screenshot from 2023-05-09 17-46-23](https://github.com/AstroNvim/AstroNvim/assets/124213816/52004387-20a3-4754-b5e0-652a3c348e91)
}

**Comment by mehalter** [comment]
Also, here is a link to the LuaSnip documentation for the lua loader if that helps: https://github.com/L3MON4D3/LuaSnip/blob/b4bc24c4925aeb05fd47d2ee9b24b7f73f5d7e32/doc/luasnip.txt#L2225

**Comment by basava70** [comment]
> Just tested with this minimal config:
> 
> ```lua
> return {
>   plugins = {
>     {
>       "L3MON4D3/LuaSnip",
>       config = function(plugin, opts)
>         require "plugins.configs.luasnip"(plugin, opts) -- include the default astronvim config that calls the setup call
>         require("luasnip.loaders.from_lua").lazy_load { paths = { "./lua/user/snippets" } } -- load snippets paths
>       end,
>     },
>   },
> }
> ```
> 
> inside of `~/.config/nvim/lua/user/snippets` I added an `all.lua` that has this content:
> 
> ```lua
> local ls = require "luasnip"
> local s = ls.snippet
> local t = ls.text_node
> 
> return {
>   s("trig", t "loaded!!"),
> }
> ```
> 
> then I opened just a blank buffer and typed `trig`
> 
> ![2023-05-09_11:53:08_screenshot](https://user-images.githubusercontent.com/1591837/237151348-82900836-b370-424e-b94c-dbb4b0bd2d4d.png)
> 
> Hopefully this minimal example helps you out! I would look at your files and make sure the file name matches your filetypes that you want to have the snippet. Definitely a good idea to start with as minimal of an example as you can to show it is working. If you have further questions I would recommend checking out the Discord as there are many more people who can help out and have probably done similar things.
> 
> Also one note, you want your `vimtek` function to be an `init` function rather than a `config` function, just change `config =` to `init =`, typically these vimscript plugins do want the variables to be set before the plugin is loaded. Not sure because I don't use the plugin or know if you are having issues with it, but it might be a good idea.

Thanks for the quick reply, but its still not working with the minimal config. Are you sure u added nothing for cmp ? in the lua/user/ folder? just with the  base user config folder you got the "trig" snippet working?

**Comment by mehalter** [comment]
@aromero3003 looks like you have a few different issues going on here.

1. make sure you have `enable_autosnippets = true` in your `luasnip` options
2. your definition of your auto snippet is wrong, you need to specify the `trig`

`user/init.lua`:
```lua
return {
  plugins = {
    {
      "L3MON4D3/LuaSnip",
      opts = {
        enable_autosnippets = true,
      },
      config = function(plugin, opts)
        require "plugins.configs.luasnip"(plugin, opts) -- include the default astronvim config that calls the setup call
        require("luasnip.loaders.from_lua").lazy_load { paths = { "./lua/user/snippets" } } -- load snippets paths
      end,
    },
  },
}
```

`user/snippets/all.lua`:

```lua
local ls = require "luasnip"
local s = ls.snippet
local t = ls.text_node

return {
  s({ trig = "trig", snippetType = "autosnippet" }, t "loaded!!"),
}
```

recording: https://asciinema.org/a/zOCC2otw9uoOB9eUmN8CVUa0P

**Comment by mehalter** [comment]
@aromero3003 be sure to carefully go through the LuaSnip documentation that I linked in a previous comment to figure out the correct way to define snippets.

**Comment by aromero3003** [comment]
Thanks!! I forgot to add the trig key when I made the example. It's working now

**Comment by goququ** [comment]
@mehalter 
> inside of ~/.config/nvim/lua/user/snippets I added an all.lua that has this content:

Does it work with `$XDG_CONFIG_HOME/astronvim/lua/user/snippets` folder? Can't make this plugin work with it

**Comment by mehalter** [comment]
@goququ you can do something like this when you set up the snippets and provide a full path to the file. I believe by default a relative path is resolved by `luasnip` in relation to the `~/.config/nvim` folder. Here is an example:

```lua
        require("luasnip.loaders.from_vscode").lazy_load {
          paths = { vim.fn.expand "$XDG_CONFIG_HOME/astronvim/lua/user/snippets" },
        } -- load snippets paths
```

**Comment by goququ** [comment]
> ```lua
> require("luasnip.loaders.from_vscode").lazy_load {
>   paths = { vim.fn.expand "$XDG_CONFIG_HOME/astronvim/lua/user/snippets" },
> } -- load snippets paths
> ```

It's alive! Many thanks 🙏

**Comment by aravezskinteeth** [comment]
I tried all of this but I can't still get my snippets to load.

I read the **LuaSnip** and **Astronvim** documentation, I followed it and I still can't get my snippets to load. 

In `user/plugins/luasnip/luasnip.lua` I have the following:

```lua
return {
  plugins = {
    { -- override LuaSnip
      "L3MON4D3/LuaSnip",
      opts = {
        enable_autosnippets = true,
      },
      config = function(plugin, opts)
        require "plugins.configs.luasnip"(plugin, opts) -- include the default astronvim config that calls the setup call
        -- opts parameter is the default options table
        require("luasnip.loaders.from_lua").lazy_load { paths = { "./user/snippets" } } -- load snippets paths
      end,
    },
  },
}
```

My `all.lua` snippet looks like this:
```lua
local ls = require("luasnip")
local s = ls.snippet
local t = ls.text_node


return {
  s({ trig = "trig", snippetType = "autosnippet" }, t "loaded!!"),
}
```

If it helps I'm also using the `vimtex` plugin (`users/plugins/vimtex.lua`)
```lua
return {
  -- VImTex configuration
  {
    'lervag/vimtex',
      init = function ()
        vim.g.vimtex_view_method = "zathura"
      end,
      event = "BufRead",
  },
}
```

And to be fair, I was following [this guide](https://www.ejmastnak.com/tutorials/vim-latex/luasnip/). Some of the tutorial latex snippets included a `get_visual` function, and to not get repetitive, he added it this file `luasnip-helper-funcs.lua`, which I added inside of `user/plugins/luasnip/`

```lua
local M = {}

local ls = require("luasnip")
local sn = ls.snippet_node
local i = ls.insert_node

function M.get_ISO_8601_date()
  return os.date("%Y-%m-%d")
end

function M.get_visual(args, parent)
  if (#parent.snippet.env.SELECT_RAW > 0) then
    return sn(nil, i(1, parent.snippet.env.SELECT_RAW))
  else
    return sn(nil, i(1, ''))
  end
end

return M
```

You guys can take a look at my [nvim config](https://github.com/aravezskinteeth/astronvim-config).
