### ISSUE TITLE
Cannot comment on javascript files without error

### ISSUE THREAD

**Issue by SamueleSamarxhiu** [AstroNvim/AstroNvim#1990]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Ubuntu 22.04

### Terminal/GUI

terminal

### AstroNvim Health

AstroNvim version: 3.20
Nvim version: v0.9.0

### Describe the bug

whenever I try to place a comment in my JavaScript file it appears the following error that I will show on the screenshot because im not able to copy it from the terminal

### Steps to Reproduce

just open a javascrpt file and try to comment in it

### Expected behavior

I expected the comments on the editor to work but instead appears this erro as soon as I put two slashes (//)

### Screenshots

![Screenshot from 2023-06-11 10-41-15](https://github.com/AstroNvim/AstroNvim/assets/73663949/c3ab929c-2c8a-46ba-aba1-e5eb8e29e110)

**Comment by SamueleSamarxhiu** [comment]
I tried to reinstall latest neovim version 0.9 and Astronvim but the problem still presist

**Comment by mehalter** [comment]
You need to reinstall your javascript parser. You can do this with `:TSInstall javascript`

**Comment by electricjones** [comment]
I am having the same issue with rust and a re-install did not work.

**Comment by mehalter** [comment]
could you try updating to AstroNvim v3.22.1 @electricjones

**Comment by electricjones** [comment]
I am on version 3.22.1. I just updated when I saw the other ticket closed. I also ran a Lazy Sync. I suppose there may be a cache to be busted somewhere.

**Comment by mehalter** [comment]
Hm, I can't seem to replicate this at all 🤔 have you tried with a stock installation and no user configuration? It should be fixed with reinstalling the treesitter parser and not with lazy sync

**Comment by SamueleSamarxhiu** [comment]
I reinstalled the javascript parser but unfortunately the error is still there

**Comment by mehalter** [comment]
I'll leave this reopened for now. I haven't been able to replicate across nightly/stable and various Neovim versions. Hopefully someone can do some more investigating and provide good replication instructions

**Comment by electricjones** [comment]
I don't think I can provide better replication instructions, but I think my issue is that I used snap to install neovim. When I uninstall the treesitter rust I get an error that it can't remove a file. I'd bet that file is the sticky one that's the problem.

**Comment by SamueleSamarxhiu** [comment]
same thing, I installed neovim from snap, and I think that is probably the reason, as another guy already opened a similar issue saying that he installed neovim from snap

**Comment by electricjones** [comment]
Yeah, my issue is with snap, not with astrovim (anymore). Thank you for resolving this. I'll figure out my snap problem.

**Comment by SamueleSamarxhiu** [comment]
I have the same issue, I'll try download neovim latest release from the github repository instead from the snap store, and see if the problem presists

**Comment by SamueleSamarxhiu** [comment]
@electricjones @mehalter ok so basically it fixed by having neovim installed from a source that is not snap. Snap is bascially causing the problem

**Comment by electricjones** [comment]
Yeah, I think the issue is that when Astronvim was grabbing the wrong version of TreeSitter it upgraded when we didn't want to. And, for some reason, snap is not letting us downgrade.

@mehalter I think this can be closed. Thank you!
